name: Linting and types checking
on:
  push:
    branches-ignore:
      - main
jobs:
  check-up:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Get code from repository
        uses: actions/checkout@v4
      - name: Create .env file
        run: |
          echo 'DB_URL'=${{ secrets.DB_URL }} > .env
          echo 'JWT_SECRET_KEY'=${{ secrets.JWT_SECRET_KEY }} >> .env
          echo 'REDIS_CACHE'=${{ secrets.REDIS_CACHE }} >> .env
          echo 'HOST'=${{ secrets.HOST }} >> .env
      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip3 install -r requirements.txt
      - name: Types checking via MyPy
        run: |
          source venv/bin/activate
          mypy . --explicit-package-bases
      - name: Linting via Pylint
        run: | 
          source venv/bin/activate
          pylint .
