name: Linting and types checking
on: [push, workflow_dispatch]
jobs:
  check-up:
    runs-on: ubuntu-latest
    environment: development
    env:
      KIS_DB_URL: ${{ secrets.KIS_DB_URL }}
    steps:
      - name: Get code from repository
        uses: actions/checkout@v4
      - name: Create .env file
        run: |
          GITHUB_ENV='.env'
          echo 'KIS_DB_URL'=${{ env.KIS_DB_URL }} >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip3 install -r requirements.txt
      - name: Testing via PyTest
        run: |
          python3 -m venv venv
          source venv/bin/activate
          playwright install chromium
          playwright install-deps chromium
          pytest .