name: Testing
on: [push, workflow_dispatch]
jobs:
  check-up:
    runs-on: ubuntu-latest
    environment: development
    env:
      KIS_DB_URL: ${{ secrets.KIS_DB_URL }}
      TESTING: 'True'
    steps:
      - name: Get code from repository
        uses: actions/checkout@v4
      - name: Create .env file
        run: |
          GITHUB_ENV='.env'
          echo 'KIS_DB_URL'=${{ env.KIS_DB_URL }} >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip3 install -r requirements.txt
      - name: Testing via PyTest
        run: |
          python3 -m venv venv
          source venv/bin/activate
          playwright install chromium
          playwright install-deps chromium
          pytest .


  auto-merge:
    runs-on: ubuntu-latest
    needs: check-up
    if: success()  # Only run if the check-up job succeeded
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: | 
          git config --global user.name 'GitHub Actions' && git config --global user.email 'actions@github.com'

      - name: Check out dev branch
        run: |
          git checkout dev
          git merge ${{ github.ref }}
          git push origin dev